services:
  sql2025-lab:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sql2025-lab
    hostname: sql2025-lab
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "14333:1433"
    volumes:
      - sql2025_lab_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql2025_lab_data: